export { EditOrchestratorService } from "./editOrchestrator.service";
export { TargetResolverService } from "./targetResolver.service";

export type {
  DocxParagraphNode,
  EditAction,
  EditApplyRequest,
  EditApplyResult,
  EditConstraintSet,
  EditDiffPayload,
  EditDomain,
  EditExecutionContext,
  EditOperator,
  EditPolicy,
  EditPlan,
  EditPlanDiagnostics,
  EditPlanRequest,
  EditPlanResult,
  EditPreviewRequest,
  EditPreviewResult,
  EditRationale,
  EditReceipt,
  EditRevisionStore,
  EditTelemetry,
  EditDiffChange,
  ResolvedTarget,
  ResolvedTargetCandidate,
  SheetsTargetNode,
  SlidesTargetNode,
  UndoRequest,
  UndoResult,
} from "./editing.types";
